2018/01 - Speech Synthesis and
fegemo/cefet-web-weblot pull request #33
Opened 2018-05-23 23:17 UTC by lauradebella

2018-05-24 01:41 UTC, fegemo requested changes
@lauradebella e @luisccf vejam os comentários que fiz no PR de vocês. Peço, também, que excluam os arquivos .DS_Store e incluam uma entrada no .gitignore pra esses arquivos.

2018-05-24 01:41 UTC, fegemo commented on apis.json
> +      "screenshot": "apis/speech-synhesis/images/screenshot.png",
Faltou um 't' em 'apis/speech-synthesis' nesta linha e na de baixo.

2018-05-24 01:41 UTC, fegemo commented on apis/speech-recognition/index.html
> +      <select id="select_language" onchange="updateCountry()"></select>
O exemplo não está funcionando... Quando trocamos a língua:

![image](https://user-images.githubusercontent.com/1650402/40459752-85957aa2-5ed9-11e8-9896-9063ad996cef.png)

2018-05-24 01:41 UTC, fegemo commented on apis/speech-recognition/scripts/script.js
> +        start_img.src = 'mic.gif';
Não está encontrando a imagem (dá 404).

2018-05-24 01:41 UTC, fegemo commented on apis/speech-recognition/index.html
> +  <a href="http://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html">
Por quê este link?

2018-05-24 01:41 UTC, fegemo commented on apis/speech-recognition/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Overlock|Chewy">
Está incluindo duas fontes, mas não usa nenhuma delas.

2018-05-24 01:41 UTC, fegemo commented on apis.json
> +    },
Esta vírgula ao final do último elemento de um _array_ torna o arquivo um JSON inválido.

2018-06-10 16:24 UTC, lauradebella commented
@fegemo modificações realizadas 👍

2018-06-15 17:09 UTC, merged